import nodemailer from "nodemailer";

// Lazy initialize transporter to prevent cold-start failures if env vars are missing during build
let transporter = null;
const getTransporter = () => {
  if (!transporter) {
    if (!process.env.MY_EMAIL || !process.env.MY_PASSWORD) {
      console.warn("⚠️ Warning: SMTP credentials (MY_EMAIL / MY_PASSWORD) are not configured in environment variables!");
    }
    transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.MY_EMAIL,
        pass: process.env.MY_PASSWORD,
      },
    });
  }
  return transporter;
};

export const sendContactMail = async (req, res) => {
  try {
    const { fname, lname, email, phone, product, message } = req.body;

    // ✅ Robust input validation
    if (!fname || !lname || !email || !phone || !product || !message) {
      return res.status(400).json({ error: "All fields are required. Please check your inputs." });
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return res.status(400).json({ error: "Please enter a valid email address." });
    }

    const receiverEmail = process.env.MY_RECEIVER_EMAIL || process.env.MY_EMAIL;
    if (!receiverEmail) {
      return res.status(500).json({ error: "Receiver email configuration is missing on the server." });
    }

    // ✅ Compose beautiful HTML email body
    const htmlBody = `
      <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #ddd; border-radius: 8px; overflow: hidden;">
        <div style="background-color: #5A3D3D; color: #fff; padding: 20px; text-align: center;">
          <h2 style="margin: 0; font-size: 24px; letter-spacing: 1px;">☕ CodeNap Café</h2>
          <p style="margin: 5px 0 0; font-size: 14px; opacity: 0.9;">New Contact Inquiry Received</p>
        </div>
        <div style="padding: 20px;">
          <p style="font-size: 16px;">Hello Team,</p>
          <p>You have received a new contact inquiry with the following details:</p>
          
          <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; width: 140px; border-bottom: 1px solid #eee;">First Name:</td>
              <td style="padding: 8px 0; border-bottom: 1px solid #eee;">${fname}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; border-bottom: 1px solid #eee;">Last Name:</td>
              <td style="padding: 8px 0; border-bottom: 1px solid #eee;">${lname}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; border-bottom: 1px solid #eee;">Email Address:</td>
              <td style="padding: 8px 0; border-bottom: 1px solid #eee;"><a href="mailto:${email}" style="color: #E5594C; text-decoration: none;">${email}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; border-bottom: 1px solid #eee;">Phone Number:</td>
              <td style="padding: 8px 0; border-bottom: 1px solid #eee;">${phone}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; border-bottom: 1px solid #eee;">Product Interest:</td>
              <td style="padding: 8px 0; border-bottom: 1px solid #eee; text-transform: capitalize;">${product}</td>
            </tr>
          </table>

          <div style="background-color: #f9f9f9; padding: 15px; border-left: 4px solid #E5594C; border-radius: 4px; margin-top: 20px;">
            <h4 style="margin: 0 0 10px; color: #5A3D3D;">Customer Message:</h4>
            <p style="margin: 0; white-space: pre-line; font-style: italic;">"${message}"</p>
          </div>
        </div>
        <div style="background-color: #f4f4f4; text-align: center; padding: 15px; font-size: 12px; color: #777; border-top: 1px solid #ddd;">
          <p style="margin: 0;">This email was automatically generated by your CodeNap Café portal.</p>
        </div>
      </div>
    `;

    const mailOptions = {
      from: `"CodeNap Café Inquiry" <${process.env.MY_EMAIL}>`,
      to: receiverEmail,
      subject: `✉️ New Contact Form submission from ${fname} ${lname}`,
      html: htmlBody,
    };

    await getTransporter().sendMail(mailOptions);

    res.status(200).json({ 
      success: true,
      message: "✅ Thanks for reaching out! We'll get back to you shortly. Enjoy your coffee! ☕" 
    });
  } catch (error) {
    console.error("❌ Error sending contact mail:", error);
    res.status(500).json({ error: "Failed to send message. Please try again later." });
  }
};
