import nodemailer from "nodemailer";

// Lazy initialize transporter
let transporter = null;
const getTransporter = () => {
  if (!transporter) {
    if (!process.env.MY_EMAIL || !process.env.MY_PASSWORD) {
      console.warn("⚠️ Warning: SMTP credentials (MY_EMAIL / MY_PASSWORD) are missing!");
    }
    transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.MY_EMAIL,
        pass: process.env.MY_PASSWORD,
      },
    });
  }
  return transporter;
};

export const sendReservationMail = async (req, res) => {
  try {
    const { customerName, person, date, time } = req.body;

    // ✅ Validate required fields
    if (!customerName || !person || !date || !time) {
      return res.status(400).json({ error: "All fields are required. Please check your reservation details." });
    }

    const receiverEmail = process.env.MY_RECEIVER_EMAIL || process.env.MY_EMAIL;
    if (!receiverEmail) {
      return res.status(500).json({ error: "Receiver email configuration is missing on the server." });
    }

    // ✅ Compose stylized HTML email body
    const htmlBody = `
      <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #ddd; border-radius: 8px; overflow: hidden;">
        <div style="background-color: #614343; color: #fff; padding: 20px; text-align: center;">
          <h2 style="margin: 0; font-size: 24px; letter-spacing: 1px;">🍽️ Table Reservation</h2>
          <p style="margin: 5px 0 0; font-size: 14px; opacity: 0.9;">A customer requested a booking</p>
        </div>
        <div style="padding: 20px;">
          <p style="font-size: 16px;">Hello Team,</p>
          <p>A new table reservation request has been submitted:</p>
          
          <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; width: 150px; border-bottom: 1px solid #eee;">Customer Name:</td>
              <td style="padding: 8px 0; border-bottom: 1px solid #eee;">${customerName}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; border-bottom: 1px solid #eee;">Number of Guests:</td>
              <td style="padding: 8px 0; border-bottom: 1px solid #eee; font-weight: bold; color: #E5594C;">${person} Persons</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; border-bottom: 1px solid #eee;">Date:</td>
              <td style="padding: 8px 0; border-bottom: 1px solid #eee;">${date}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; border-bottom: 1px solid #eee;">Requested Time:</td>
              <td style="padding: 8px 0; border-bottom: 1px solid #eee;">${time}</td>
            </tr>
          </table>
        </div>
        <div style="background-color: #f4f4f4; text-align: center; padding: 15px; font-size: 12px; color: #777; border-top: 1px solid #ddd;">
          <p style="margin: 0;">This email was automatically generated by your CodeNap Café portal.</p>
        </div>
      </div>
    `;

    const mailOptions = {
      from: `"CodeNap Café Reservations" <${process.env.MY_EMAIL}>`,
      to: receiverEmail,
      subject: `🍽️ Table Reservation by ${customerName} for ${person} Guests`,
      html: htmlBody,
    };

    await getTransporter().sendMail(mailOptions);

    res.status(200).json({
      success: true,
      message: "✅ Your table is booked. We look forward to serving you the perfect cup! ☕🍽️",
    });
  } catch (error) {
    console.error("❌ Error sending reservation email:", error);
    res.status(500).json({ error: "Failed to send reservation email. Please try again later." });
  }
};
