import nodemailer from "nodemailer";

// Lazy initialize transporter
let transporter = null;
const getTransporter = () => {
  if (!transporter) {
    if (!process.env.MY_EMAIL || !process.env.MY_PASSWORD) {
      console.warn("⚠️ Warning: SMTP credentials (MY_EMAIL / MY_PASSWORD) are missing!");
    }
    transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.MY_EMAIL,
        pass: process.env.MY_PASSWORD,
      },
    });
  }
  return transporter;
};

export const sendSubscribeMail = async (req, res) => {
  try {
    const { email } = req.body;

    // ✅ Validate required field
    if (!email) {
      return res.status(400).json({ error: "Email address is required." });
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return res.status(400).json({ error: "Please enter a valid email address." });
    }

    const receiverEmail = process.env.MY_RECEIVER_EMAIL || process.env.MY_EMAIL;
    if (!receiverEmail) {
      return res.status(500).json({ error: "Receiver email configuration is missing on the server." });
    }

    // ✅ Compose stylized HTML email body
    const htmlBody = `
      <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #ddd; border-radius: 8px; overflow: hidden;">
        <div style="background-color: #a8a295; color: #fff; padding: 20px; text-align: center;">
          <h2 style="margin: 0; font-size: 24px; letter-spacing: 1px;">📬 New Subscription</h2>
          <p style="margin: 5px 0 0; font-size: 14px; opacity: 0.9;">Someone joined the Coffee Community!</p>
        </div>
        <div style="padding: 20px;">
          <p style="font-size: 16px;">Hello Team,</p>
          <p>You have a new subscriber to your newsletter list:</p>
          
          <div style="background-color: #f9f9f9; padding: 15px; border-radius: 6px; border-left: 4px solid #a8a295; margin: 20px 0; text-align: center;">
            <p style="margin: 0; font-weight: bold; font-size: 18px;">
              Subscriber Email: <a href="mailto:${email}" style="color: #E5594C; text-decoration: none;">${email}</a>
            </p>
          </div>
        </div>
        <div style="background-color: #f4f4f4; text-align: center; padding: 15px; font-size: 12px; color: #777; border-top: 1px solid #ddd;">
          <p style="margin: 0;">This email was automatically generated by your CodeNap Café portal.</p>
        </div>
      </div>
    `;

    const mailOptions = {
      from: `"CodeNap Café Community" <${process.env.MY_EMAIL}>`,
      to: receiverEmail,
      subject: `📬 New Newsletter Subscription from ${email}`,
      html: htmlBody,
    };

    // ✅ Replaced callback-based transporter with async/await
    await getTransporter().sendMail(mailOptions);

    res.status(200).json({
      success: true,
      message: "✅ Thanks for subscribing to our updates. Fresh brews and news are coming your way! ☕",
    });
  } catch (error) {
    console.error("❌ Error sending subscription email:", error);
    res.status(500).json({ error: "Server error while subscribing. Please try again later." });
  }
};